sudo: required
services:
  - docker

before_install:
  - echo "testing some stuff here"

script:
  - docker ps -a

after_success:
  # build images
  - docker build -t kristapsvitols/super-api ./api
  - docker build -t kristapsvitols/super-client ./client
  - docker build -t kristapsvitols/super-nginx ./nginx
  # login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push images
  - docker push kristapsvitols/super-api
  - docker push kristapsvitols/super-client
  - docker push kristapsvitols/super-nginx

deploy:
  provider: script
  script: echo "Y" | bash ./deploy.sh
  on:
    branch: master